version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    schedule:
      interval: monthly
