- id: devmoji
  name: devmoji
  description: Decorate commit messages with emojis.
  entry: devmoji -e
  language: node
  additional_dependencies:
    - devmoji@2.4.1
  pass_filenames: false
  stages: [prepare-commit-msg]
